Creating NumPy Array


In [4]:
#Single dimensional array
import numpy as np

x1 = np.array([10,20,30,40])
x1

numpy.ndarray

In [2]:
#Multidimensional array
import numpy
x2 = numpy.array([[10,20,30,40],[40,30,20,10]])
x2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

Initializing Numpy array with zeros

In [7]:
x3 = np.zeros([2,3])
x3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
x4 = np.zeros([5,6])
x4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
#initializing Numpy array with same number
x5 = np.full([3,3],5)
x5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

Initializing Numpy array withing a range

In [9]:
x1 = np.arange(10,30)
x1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [10]:
# specify range and stepping it
#the first parameter (10) is inclusive while the last one is exclusive 
x2 = np.arange(10,40,3)
x2

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

Initializing Numpy random Array

In [13]:
# the starting the point and the end point and the last parameter refers to how numbers within the specified range
x1 = np.random.randint(10, 100, 20)
x1

array([16, 28, 67, 23, 92, 85, 99, 85, 95, 87, 49, 73, 54, 22, 97, 36, 60,
       58, 39, 35])

Checkling the shape of Numpy array


In [15]:
n1 = np.array([[1,2,3],[2,3,4]])
n1.shape

(2, 3)

In [16]:
n1.shape = (3,2)
n1

array([[1, 2],
       [3, 2],
       [3, 4]])

Joining Numpy Arrays

In [17]:
# joining vertically using vstack() method
n2 = np.array([1,2,3,4])
n3 = np.array([5,6,7,8])
np.vstack((n2,n3))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
# joining horizontally using hstack() method
n2 = np.array([1,2,3,4])
n3 = np.array([5,6,7,8])
np.hstack((n2,n3))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
# joining  using column_stack() method
n2 = np.array([1,2,3,4])
n3 = np.array([5,6,7,8])
np.column_stack((n2,n3))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Numpy Intersection & Difference

In [2]:
#this will bring out the common element of the two array
import numpy as np
num = np.array([5,6,7,8,9,10,11])
num1 = np.array([10,20,30,5,6,8])
np.intersect1d(num, num1)

array([ 5,  6,  8, 10])

In [3]:
# this will show the element in first array and not in the second array
num = np.array([5,6,7,8,9,10,11])
num1 = np.array([10,20,30,5,6,8])
np.setdiff1d(num, num1)


array([ 7,  9, 11])

In [5]:
# this will show element present in second array and  not in the first array
num = np.array([5,6,7,8,9,10,11])
num1 = np.array([10,20,30,5,6,8])
np.setdiff1d(num1, num)

array([20, 30])

Addition Of Numpy Arrays

In [2]:
# sum of all values of the array
import numpy as np
num = np.array([10,20])
num2 = np.array([30,15])
np.sum([num,num2])

75

In [3]:
# adding based on axis vertically
num = np.array([10,20])
num2 = np.array([30,15])
np.sum([num,num2], axis=0)

array([40, 35])

In [4]:
#adding based on horizontal axis
num = np.array([10,20])
num2 = np.array([30,15])
np.sum([num,num2], axis=1)

array([30, 45])

In [5]:
# doing basic addition
n1 = np.array([10, 1, 15])
n1 = n1 + 5
n1

array([15,  6, 20])

In [7]:
# doing basic subtraction
n1 = np.array([10, 1, 15])
n1 = n1 - 5
n1

array([ 5, -4, 10])

In [8]:
# doing basic division
n1 = np.array([10, 2, 14])
n1 = n1 / 2
n1

array([5., 1., 7.])

In [6]:
# doing basic multiplication
n1 = np.array([10, 1, 15])
n1 = n1 * 5
n1

array([50,  5, 75])

Standard math functions

In [10]:
import numpy as np
x1 = np.array([10, 20, 12, 5, 4, 11])
np.mean(x1)

10.333333333333334

In [3]:
import numpy as np
x2 = np.array([10, 20, 12, 5, 4, 11])
np.median(x2)

10.5

In [8]:
import numpy as np
x1 = np.array([10, 20, 12, 5, 4, 11])
np.std(x1)

5.2493385826745405

Numpyarray save and load

In [12]:
import numpy as np
m1 = np.array([10,13,15,19,21])
np.save('Numpy_save', m1)

In [13]:
m2 = np.load('Numpy_save.npy')
m2

array([10, 13, 15, 19, 21])